# Generated by Django 5.0.6 on 2024-06-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBook', '0002_rename_autor_autores_rename_editorial_editoriales'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='resena',
            field=models.CharField(default='Sin reseñas', max_length=300),
        ),
    ]
