# Generated by Django 5.0.6 on 2024-06-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBook', '0003_libro_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='resena',
            field=models.BigIntegerField(),
        ),
    ]
