# Generated by Django 5.0.6 on 2024-06-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBook', '0006_alter_libro_resena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='resena',
            new_name='reseña',
        ),
    ]
